# Deployment of the app-gw-multi-tenant-app-service solution

name: deploy-app-gw-multi-tenant-app-service

on: workflow_dispatch

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./drop"

jobs:
  deploy_apiapp:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Dotnet 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: dotnet build and publish
        run: |
          dotnet build ./app-gw-multi-tenant-app-service/apiapp/apiapp.csproj --configuration Release
          dotnet publish ./app-gw-multi-tenant-app-service/apiapp/apiapp.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/apiapp'

      - name: deploy-apiapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: apiapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE__APIAPP }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/apiapp'

      
