name: hm-ext-funcapi-python-flask-cd

on: 
  push:
    branches:
      - 'main'
    paths:
      - 'funcapi-python-flask/**'
  workflow_dispatch:

env: 
  PYTHON_VERSION: 3.9
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './funcapi-python-flask/'
  AZURE_FUNCTIONAPP_NAME: 'hmapfuncb'
  AZURE_RESOURCE_GROUP: 'hm-assortment-profiling-b'
  APPREG_DISPLAY_NAME: 'funcapi-python-flask-api'
  AZURE_TENANT_ID: 'MngEnv319828'

jobs:
    
  deploy-azure-function:
     # use a linux runner for bicep deployments
    runs-on: ubuntu-latest
#    needs: create-user-and-deploy-keyvault

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.EXT_FUNCAPI_PYTHON_FLASK_CD }}

      - name: 'Deploy Function App Infrastructure' 
        run: |
          cd ./funcapi-python-flask/bicep
          
          az deployment sub create \
            --location 'centralus' \
            --name 'full-deployment-'$(date "+%Y-%m-%d_%H%M%S") \
            -f main.bicep \
            -p main.parameters.json \
            -p appRegClientId=${{ env.EXT_FUNCAPI_PYTHON_FLASK_CLIENT_CLIENTID }}

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: get-publish-profile
        shell: bash
        run: |
          PUBLISH_PROFILE=$(az webapp deployment list-publishing-profiles -g ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --query "[?profileName=='${{ env.AZURE_FUNCTIONAPP_NAME }} - Web Deploy'] | [0]" | tr '\n' ' ') 
          echo "::add-mask::$PUBLISH_PROFILE"
          #echo "::set-output name=publish-profile::$PUBLISH_PROFILE"

      - name: 'Package and publish'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ steps.get-publish-profile.outputs.publish-profile }}