name: hm-funcapi-python-flask-cd

on: workflow_dispatch

env: 
  PYTHON_VERSION: 3.9
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './funcapi-python-flask/'
  AZURE_FUNCTIONAPP_NAME: 'hmapfunca'

jobs:

  deploy function infra:
     # use a linux runner for bicep deployments
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.FUNCAPI_PYTHON_FLASK_CD }}

      - run: |
          cd ./funcapi-python-flask/bicep
          az deployment sub create \
            --location 'centralus' \
            --name 'full-deployment-'$(date "+%Y-%m-%d_%H%M%S") \
            -f main.bicep \
            -p main.parameters.json

  deploy function app:
    runs-on: ubuntu-latest
    depends-on: deploy function infra

    steps:
      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Package and publish'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}